Configure passport and added currentUser
Ezex360/Chat pull request #5
Opened 2020-03-10 12:57 UTC by Ezex360

2020-03-12 11:21 UTC, nahudalla requested changes

2020-03-12 11:21 UTC, nahudalla commented on src/controllers/graphql/user-controller.js
> +}
You can write this in one line with shorter syntax:
```suggestion
export const currentUser = (_, params, { user }) => user
```

2020-03-12 11:21 UTC, nahudalla commented on src/index.js
> +  const user = await models.user.findOne({where: { id: jwtPayload.sub }})
Missing spaces here. Did you run the linter?
```suggestion
  const user = await models.user.findOne({ where: { id: jwtPayload.sub } }) 
```

2020-03-13 12:17 UTC, rdemasi approved these changes

2020-03-17 15:37 UTC, nahudalla approved these changes

2020-03-17 15:38 UTC, merged